#Number of days to run simulation
NUMBER_OF_DAYS: 1095 # 365 means 1 year, 730 means 2 years,and 1095 means 3 years.

# Paths to input and output files.
EXCEL_PATH: "data/averagePerDay_v5.xlsx"
EXCEL_PATH_NEWDATA: "data/Patients_data3.xlsx" # This is modfied version of "For Nick-Nov19-FindMyBed-transportData 2021 to 2023-Bed Type-hospital options" file.

# Paths to the output files.
REPORT: "output/report.pdf"
TABLE: "output/patients_tables.xlsx"

INTENSIVE_OCCUPANCY_THRESHOLDS:
  CHU-SJ: 0.95
  CHUQ: 0.95
  CHUS: 0.95
  CUSM: 0.95
  HGJ: 0.95
  HMR: 0.95

INTERMEDIATE_OCCUPANCY_THRESHOLDS:
  CHU-SJ: 0.95
  CHUQ: 0.95
  CHUS: 0.95
  CUSM: 0.95
  HGJ: 0.95
  HMR: 0.95

WEIGHT_OF_SORTING_BY_DISTANCE : 1.0